export const WORK_ORDER_STATUS = {
  UNASSIGNED: 'UNASSIGNED',
  QUOTE_ACCEPTED: 'QUOTE_ACCEPTED',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
} as const;

export const WORK_ORDER_TYPE = {
  CHECKOUT_CLEANING: 'CHECKOUT_CLEANING',
  ADDITIONAL_REQUEST: 'ADDITIONAL_REQUEST',
} as const;

export const ASSIGNMENT_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;

export const TASK_EXECUTION_STATUS = {
  DONE: 'DONE',
  NOT_DONE: 'NOT_DONE',
  SKIPPED: 'SKIPPED',
} as const;

export const SERVICE_EXECUTION_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const REJECTION_REASON_TYPE = {
  SERVICE_REJECTION: 'SERVICE_REJECTION',
  TASK_NOT_DONE: 'TASK_NOT_DONE',
} as const;

export const RESERVATION_STATUS = {
  UPCOMING: 'UPCOMING',
  CHECKIN_DAY: 'CHECKIN_DAY',
  ACTIVE: 'ACTIVE',
  CHECKOUT_DAY: 'CHECKOUT_DAY',
  COMPLETED: 'COMPLETED',
} as const;

export const PERIODIC_INSTANCE_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
} as const;

export const SYNC_OPERATION_STATUS = {
  PENDING: 'PENDING',
  SYNCED: 'SYNCED',
  CONFLICT: 'CONFLICT',
  ERROR: 'ERROR',
} as const;
